---

-name : set up db server
 hosts : dbserver
 become : yes
 task :
   - name : install mariadb-server
     ansible.builtin.yum:
       name : mariadb-server 
       state : present

    - name : start and enable mariadb service
      ansible.builtin.service:
         name : mariadb
         state : started
         enabled  : yes

    - name: Create a new database with name 'accounts'
      community.mysql.mysql_db :  # ansible-galaxy collection install community.mysql (install in control machine)
         name : accounts
         state : present
         login_unix_socket : /var/lib/mysql/mysqld.sock

    - name: Create database user with name 'vprofile' 
      mysql_user :   # mysql_user – Adds or removes a user from a MySQL database
        name : vprofile
        password : mydatabase
        priv : '*.*:ALL'
        state : present
        login_unix_socket : /var/lib/mysql/mysqld.sock

    - name : install pymysql
      ansible.builtin.yum:
        name : python3.7-pymysql  #( yum search python | grep mysql)
        state : present