---
- name: Provisioning Server 
  hosts: all
  become: yes
  tasks:
    - name: Install NTP on Centos 
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP on Ubuntu
      apt:
         name: "{{item}}"
         state: present
         update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start & enable NTP on CentOS
      service:
        name: Chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentsOS"
      notify:
        - Restart NTP on CentOS
        

    - name: Start & enable NTP on Debian
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
      notify:
        - Restart NTP on Ubuntu

    - name: Banner file /etc/motd
      copy:
        content: "This {{ansible_distribution}} is Managed by Ansible.\n"
        dest: /etc/motd

    - name: Deploy NTP conf file on CentOS
      template:
         src: templates/ntpconf_CentOS
         dest: /etc/chrony.conf
         backup: yes
      when: ansible_distribution == "CentOS"

    - name: Deploy NTP conf file for Ubuntu
      template:
         src: templates/ntpconf_ubuntu  # cat etc/ntp.conf (ubuntu server) ; control machine copy (vim  templates/ntpconf_ubuntu)
         dest: /etc/ntp.conf
         backup: yes
      when: ansible_distribution == "ubuntu"

handlers:
    - name: Restart NTP on CentOS
      service:
        name: chronyd
        state: restarted
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Restart NTP on Ubuntu
      service:
         name: ntp
         state: restarted
         enabled: yes
      when: ansible_distribution == "ubuntu"